web/blueprints/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash, abort
from flask_login import login_required, current_user, login_user, logout_user

from web.utils import redirect_back, generate_token, validate_token, is_validate_token
from web.forms.auth import LoginForm, ForgetPasswordForm, ResetPasswordForm
from web.settings import Operations, AGNET_TYPE
from web.emails import send_reset_password_email
from web.service import user_service


auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect_back('school_agent.index')

    form = LoginForm()
    # 提交表单
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        try:
            # 检验账号密码
            user = user_service.check_user(username, password)
            if user:
                # flash('登录成功，欢迎回来', 'success')
                if user["type"] == AGNET_TYPE["SCHOOL_AGENT"]:
                    login_user(user, remember)
                    return redirect_back('school_agent.index')
                else:
                    # TODO 企业商务主页
                    flash('暂不支持企业商务登陆', 'danger')
                    return render_template('auth/login.html', form=form)
            flash('登录失败，请检测账号或者密码后重新输入', 'danger')
        except Exception as e:
            print('error when login: %s' % e)
            flash('服务器发送故障，请稍后重试', 'info')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    """
    忘记密码
    :return:
    """
    form = ForgetPasswordForm()

    if form.validate_on_submit():
        # 获取邮箱 并查询数据库
        email = form.email.data.lower()
        # TODO: 该user不是User对象
        user = user_service.get_user_by_email(email)

        # 发送到邮箱
        if user:
            token = generate_token(user, operation=Operations.RESET_PASSWORD)
            send_reset_password_email(token=token, to=email, user=user)
            flash('重置密码邮件已发送到您的邮箱，请注意查收.', 'info')
            return redirect(url_for('.login'))

        flash('邮箱输入有误，请重新输入.', 'warning')
        return redirect(url_for('.forget_password'))
    return render_template('auth/forget_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    form = ResetPasswordForm()
    # 在进入时会判断token是否过期
    if not is_validate_token(token):
        flash('该邮件已经过期，请重新发送邮件', 'info')
        return redirect(url_for('.login'))

    if form.validate_on_submit():
        email = form.email.data.lower()
        # 数据库查询
        user = user_service.get_user_by_email(email)

        if user is None:
            return redirect(url_for('school_agent.index'))
        # 传入新密码
        if validate_token(user=user, token=token, operation=Operations.RESET_PASSWORD, new_password=form.password.data):
            flash('Password updated.', 'success')
            return redirect(url_for('.login'))
        else:
            flash('Invalid or expired token.', 'danger')
            return redirect(url_for('.forget_password'))

    return render_template('auth/reset_password.html', form=form)

web/blueprints/scholar.py
from flask import Blueprint, render_template, request, flash, abort
from flask_login import current_user
import web.service.basic_info_service as basic_info_service
import datetime
import json

from web.blueprints.auth import login_required
from web.utils.mongo_operator import MongoOperator
from web.config import MongoDB_CONFIG
from web.forms.scholar import ScholarForm, ProjectForm
from web.utils import redirect_back, flash_errors
import web.service.school as school_service

scholar_bp = Blueprint('scholar', __name__)


@scholar_bp.route('/detail/<int:teacher_id>')
@login_required
def scholar_info(teacher_id):
    """
    获取专家个人信息
    :param teacher_id:
    :return:
    """
    # 返回json 序列化后的数据
    teacher = basic_info_service.get_info(teacher_id)
    team_list = basic_info_service.get_teacher_central_network(teacher_id)
    team_id_list = []
    for i in team_list:
        team_id_list.append(i['id'])
    team_info = basic_info_service.get_team_info(team_id_list)
    # 当老师id不存在时，直接报404
    if teacher is None:
        return abort(404)
    # 获取拜访记录
    visit_list = None
    try:
        mongo = MongoOperator(**MongoDB_CONFIG)
        collection = mongo.get_collection("visit_record")
        user_id = current_user.id
        # 找到对应的拜访记录信息, 按时间排序, 最多5个
        visit_info = collection.find({"user_id": user_id, "status": 1, "teacher_id": teacher_id},
                            {"_id": 0, "date": 1, "title": 1, "content": 1, "user_name": 1}).sort("date", -1).limit(5)
        # 转成列表 
        visit_list = list(visit_info)
    except Exception as e:
        print('get_visit_info error:%s' % e)
    return render_template('scholar/detail.html', teacher=teacher, visit_list=visit_list,team_info=team_info)


@scholar_bp.route('/feedback', methods=['GET'], defaults={'teacher_id': None})
@scholar_bp.route('/feedback/<int:teacher_id>', methods=['GET'])
@login_required
def feedback_get(teacher_id):
    """
    老师信息的反馈页面的GET方法 显示页面
    :return:
    """
    cur_school = None
    cur_institution = None
    form = ScholarForm()
    try:
        mongo = MongoOperator(**MongoDB_CONFIG)
        # 填充数据
        if teacher_id:
            result = mongo.get_collection('basic_info').find_one({'id': teacher_id}, {'_id': 0})
            cur_school, cur_institution = result['school'], result['institution']
            form.set_data(result)
        # 获取所有的学校
        cur_school, schools, institutions = school_service.get_schools_institutions(mongo=mongo, cur_school=cur_school)
        form.set_schools(schools, cur_school)
        form.set_institutions(institutions, cur_institution)
        title = '添加老师' if teacher_id is None else '修改老师信息'

        return render_template('scholar/teacher_feedback.html', form=form, title=title)
    except Exception as e:
        print('when feedback: %s' % e)
        abort(404)


@scholar_bp.route('/feedback', methods=['POST'], defaults={'teacher_id': None})
@scholar_bp.route('/feedback/<int:teacher_id>', methods=['POST'])
@login_required
def feedback_post(teacher_id):
    """
    老师信息反馈页面
    POST 进行数据库操作
    :return:
    """
    form = ScholarForm()
    # 根据已经提交的数据，进行数据的填充
    cur_school = form.school.data
    cur_institution = form.institution.data
    mongo = MongoOperator(**MongoDB_CONFIG)
    # 获取所有的学校
    cur_school, schools, institutions = school_service.get_schools_institutions(mongo=mongo, cur_school=cur_school)
    form.set_schools(schools, cur_school)
    form.set_institutions(institutions, cur_institution)

    if form.validate_on_submit():
        datum = form.get_data()
        datum.update({'status': 1, 'username': current_user.name,'timestamp': datetime.datetime.utcnow()})
        if teacher_id:
            datum['teacher_id'] = teacher_id
        # 写入数据库
        result = mongo.db['agent_feedback'].insert_one(datum)
        flash('操作成功，感谢您的反馈', 'success')
    else:
        flash_errors(form)

    return redirect_back()


@scholar_bp.route('/search', methods=['GET'])
@login_required
def search():
    """
    老师检索
    :return:
    """
    teachers = []
    teacher_name = ""

    if 'teacher-name' in request.args:
        teacher_name = request.args.get('teacher-name')
        # 获取老师列表
        teachers = get_teachers(teacher_name)
        #获取团队教师id,姓名
        for i in teachers:
            # i['team'] : [{"id": xxx, "name": xxx}, {...}, ...] or []
            i['team'] = basic_info_service.get_teacher_central_network(i['id'])
    return render_template('scholar/search.html', teachers=teachers, teacher_name=teacher_name)


@scholar_bp.route('/get_teachers/<teacher_name>')
@login_required
def get_teachers(teacher_name):
    """
    根据老师的名字进行数据库的搜索
    :param teacher_name: 老师名字
    :return: 如果request.args存在is_json且为True,则返回json格式的字符串，否则直接返回python数组
    """
    # 是否把结果转换成json格式的字符串,默认为False
    result = None
    is_json = request.args.get('is_json', type=bool, default=False)
    # 是否进行模糊查询
    is_like = request.args.get('is_like', type=bool, default=False)

    try:
        # 查询数据库
        mongo_operator = MongoOperator(**MongoDB_CONFIG)
        # 模糊查询
        if is_like:
            condition = {'name': {'$regex': teacher_name + '.*?'}}
        else:
            condition = {'name': teacher_name}
        scope = {'title': 1, 'school': 1, 'institution': 1, 'name': 1, '_id': 0, 'id': 1}
        generator = mongo_operator.get_collection('basic_info').find(condition, scope)
        teachers = list(generator)
        result = json.dumps(teachers) if is_json else teachers
    except Exception as e:
        print('error raised when get teacher: %s' % e)

    return result


@scholar_bp.route('/get_institutions/<school>', methods=['GET'])
@login_required
def get_institutions(school):
    """
    根据学校的名称获取学院列表
    :param school:
    :return:
    """
    mongo_operator = MongoOperator(**MongoDB_CONFIG)
    # 获取当前学校的所有院系
    condition = {'name': school}
    school = mongo_operator.get_collection('school').find_one(condition, {'_id': 0, 'institutions': 1})

    return json.dumps(school['institutions'])


@scholar_bp.route('/project', methods=['GET', 'POST'])
@login_required
def project_feedback():
    """
    项目反馈
    :return:
    """
    form = ProjectForm()
    mongo = MongoOperator(**MongoDB_CONFIG)
    # 获取所有的学校
    cur_school, schools, institutions = school_service.get_schools_institutions(mongo=mongo)

    if request.method == 'POST':
        # 出现错误，则交给flash
        if not form.validate():
            flash_errors(form)
        else:
            datum = form.get_data()
            datum.update({'timestamp': datetime.datetime.utcnow(), 'username': current_user.name, 'status': 1})
            # 写入数据库
            result = mongo.db['project_feedback'].insert_one(datum)
            flash('操作成功，感谢您的反馈', 'success')

            return redirect_back()

    return render_template('scholar/project_feedback.html', form=form, schools=schools, institutions=institutions)

web/blueprints/school.py
import json
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

import web.service.school as school_service
from web.service.school_agent_service import agent_service
from web.utils import rich_abort

school_bp = Blueprint('school', __name__)


@school_bp.route('/<school>')
@login_required
def index(school):
    """
    显示该学校的所有学院和相关的信息 树图
    :param school:
    :return:
    """
    objects = school_service.get_school_info(school)
    if objects is None:
        rich_abort(404, '未找到该学校的信息，请确认学校名称后重试')
    subjects = []
    return render_template('school/index.html', school=school, objects=objects, subjects=subjects)


@school_bp.route('/get_institution_info', methods=["GET"])
@login_required
def get_institution_info():
    """
    获取重点学院和非重点学院
    :return:
    """
    school = request.args.get("school")
    data = school_service.get_total_institutions(school)
    return json.dumps({"success": True, "data": data})


@school_bp.route('/<school>/<institution>')
@login_required
def show_institution(school, institution):
    """
    显示某一学校的学院的相关信息 主要是院系中的团队 关系图
    :param school:
    :param institution:
    :return:
    """
    # 获取院系的关系网络
    graph_json = agent_service.get_relations(school, institution)
    if graph_json is False:
        rich_abort(404, '暂时没有该学院的社交网络，请确认名称或联系管理员')
    # 获取拜访次数
    subjects = school_service.get_related_teachers(current_user.related_teacher, graph_json)
    # 获取客观信息
    objects = school_service.get_institution_info(school, institution)
    if objects is None:
        rich_abort(404, '未找到关于该学校和学院的相关信息，请确认后重试')

    return render_template('school/institution.html', school=school, institution=institution,
                           objects=objects, subjects=subjects, graph_json=json.dumps(graph_json))


@school_bp.route('/<school>/<institution>/<int:team_index>')
@login_required
def show_team(school, institution, team_index):
    """
    显示某一个团队的相关信息 关系图
    :param school: 学校名
    :param institution: 学院名
    :param team_index: 团队的索引
    :return:
    """
    graph_data, objects = school_service.get_team(school, institution, team_index)
    # 学校或者是学院不存在
    if graph_data is False:
        rich_abort(404, '暂时没有该学院的社交网络，请确认名称或联系管理员')
    # 团队不存在
    core_node = graph_data['core_node']
    if len(core_node) == 0:
        rich_abort(404, '未找到该团队')
    # 获取当前用户的有联系的老师
    subjects = school_service.get_related_teachers(current_user.related_teacher, graph_data)

    return render_template('school/team.html', school=school, institution=institution,
                           graph_data=json.dumps(graph_data), core_node=core_node,
                           objects=objects, subjects=subjects)


@school_bp.route('/edit_institution',methods=['GET'])
@login_required
def edit_institution():
    """
    跳转到选择关注的学院页面
    :return:
    """
    school = request.args.get("cur_school")
    institution = school_service.get_edit_institution(school)
    return render_template("school/edit_institution.html",school=school,institution=institution)

@school_bp.route('/update_institution_select',methods=['GET'])
@login_required
def update_institution_select():
    """
    更新数据库中学院表中用户学院slect字段
    :return:
    """
    school = request.args.get("school")
    select_institution = request.args.get("institution")
    # 处理页面获取的所选学院的字符串为列表
    selected_institution = []
    for i in select_institution.strip("[").strip("]").split(","):
        selected_institution.append(i.replace("\"", "").strip())
    institution = []
    all_institution = school_service.get_all_institution(school)
    for i in selected_institution:
        institution.append([i,1])
        if i in all_institution:
            all_institution.remove(i)
    for j in all_institution:
        institution.append([j,0])
    try:
        school_service.update_institution_select(school,institution)
        return json.dumps({"success":True})
    except:
        return json.dumps({"success":False})

web/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <title>{% block title %}Base-Template{% endblock %}</title>
        <link href="https://cdn.bootcss.com/mdui/0.4.2/css/mdui.min.css" rel="stylesheet">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap_v4.min.css') }}">

        <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
        {% block styles %}{% endblock %}
        <style>
            #alert-box-success,
            #alert-box-danger{
                position: fixed;
                width: 350px;
                top: 20%;
                left: 50%;
                transform: translateX(-175px);
                z-index: 9999;
                text-align: center;
            }
            .hidden{
                display: none;
            }
        body{
            background: #f6f6f6;
        }
        #inputGroup-sizing-sm{
            padding: 0;
            border: none;
            cursor: pointer;
        }
        #inputGroup-sizing-sm .input-group-text{
            border-right: none;
            background: white;
        }
        </style>
        <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
        
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar-header">
        <a class="navbar-brand thumbnail" href="#">Logo</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
        {% if current_user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                {{ render_nav_item('activity.manager', '活动安排') }}
                {{ render_nav_item('schedule.schedule', '日程安排') }}
                {{ render_nav_item('visit_record.manage_visit_record', '拜访记录') }}
                <li>
                    <div class="dropdown">
                        <a class="nav-item nav-link dropdown-toggle" id="schoolChoose" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            选择学校
                        </a>
                        <div class="dropdown-menu" aria-labelledby="schoolChoose">
                            {% for school in current_user.charge_school %}
                                <a class="dropdown-item" id="charge_school" href="{{ url_for('school.index', school=school) }}">{{ school }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <form class="form-inline" method="get" action="{{ url_for('scholar.search') }}">
                    <div class="input-group input-group-sm">
                        <input type="text" class="form-control" name="teacher-name" placeholder="Search for experts..."
                               aria-label="Small" aria-describedby="inputGroup-sizing-sm" style="border-right: none">
                               
                        <!-- <span class="input-group-btn"> -->
                        <button class="input-group-append" type="submit" id="inputGroup-sizing-sm">
                            <span class="input-group-text">
                                <i class="mdui-icon material-icons">&#xe8b6;</i>
                            </span> 
                        </button>
                        <!-- </span> -->
                    </div><!-- /input-group -->
                </form>
                <li>
                    <a class="nav-item nav-link {% if request.endpoint == 'reminder.info_reminder' %}active{% endif %}"
                       href="{{ url_for('reminder.info_reminder') }}">
                        <i class="mdui-icon material-icons">&#xe7f4;</i>
                        {% if unread_msg != 0 %}
                            <span class="badge" style="background-color: red; color: white">{{ unread_msg }}</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">
                        {{ current_user.name }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" role="menu">
                        <a class="dropdown-item" href="{{ url_for('school_agent.index') }}">
                            <i class="mdui-icon material-icons">&#xe88a;</i> 个人中心
                        </a>
                        <a class="dropdown-item" href="{{ url_for('scholar.feedback_get') }}">
                            <i class="mdui-icon material-icons">&#xe85e;</i> 添加老师
                        </a>
                        <a class="dropdown-item" href="{{ url_for('scholar.project_feedback') }}">
                            <i class="mdui-icon material-icons">&#xe02e;</i> 添加项目
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ url_for('school_agent.setting') }}">
                            <i class="mdui-icon material-icons">&#xe8b8;</i> 设置
                        </a>
                        <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                           <i class="mdui-icon material-icons">&#xe8ac;</i> 注销
                        </a>
                    </div>
                </li>
            </ul>
        {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="clearfix"><a class="nav-item nav-link active float-right" href="{{ url_for('auth.login') }}"><i class="mdui-icon material-icons">&#xe7fd;</i></a></li>
            </ul>
        {% endif %}
    </div>
</nav>

<main>
    {# 消息 #}
    {% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }} text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
    {% endfor %}
    {% block main %}
    {% endblock %}
</main>
<div id="alert-box-success" class="alert alert-success hidden">
    <strong><i class="mdui-icon material-icons">&#xe86c;</i><span class="alert-message">提交成功，等待管理员审核</span></strong>
</div>
<div id="alert-box-danger" class="alert alert-danger hidden">
    <strong><i class="mdui-icon material-icons">&#xe000;</i><span class="alert-message">提交失败，请稍后再试</span></strong>
</div>
<footer>
    {% block footer %}
    {% endblock %}
</footer>
<script>
    /**
 * 显示/隐藏提示框
 * @param {boolean} isSuccess 
 * @param {string} modal 模态框id, 用于隐藏模态框 
 * @param {string} message 用于显示的消息
 */
function toggle_alert(isSuccess, modal, message = ""){
    if(modal){
        $(`#${modal}`).modal("hide");
    }

    let alert_success = $("#alert-box-success");
    let alert_error = $("#alert-box-danger");
    // 显示操作成功的提示框
    if(isSuccess){
        alert_error.hide();
        
        if(message){
            alert_success.find('.alert-message').text(message);
        }

        alert_success.show(200);
        setTimeout(()=>{
            alert_success.hide(200);
        }, 2500)
    }else{
        alert_success.hide();
        
        if(message){
            alert_error.find('.alert-message').text(message);
        }

        alert_error.show(200);
        setTimeout(()=>{
            alert_error.hide(200);
        },2500);
    }
}
</script>
{% block scripts %}
    <script src="{{ url_for('static', filename='js/bootstrap_v4.min.js') }}"></script>
{% endblock %}
</body>
</html>

web/templates/visit_record.html
{% extends 'base.html' %}

{% block title %}
    拜访记录
{% endblock %}

{% block styles %}
    <style type="text/css">
        .form-group input{
            width: 300px;
            height: 45px;
            font-size: 23px;
        }
        .form-group textarea{
            height: 200px;
            width: 600px;
            font-size: 23px;
        }
        #add-new-record{
            text-align: center;
            cursor: pointer;
        }
        #add-new-record:hover{
            color:#007bff;
        }
        #exampleModal .input-group{padding: 6px 0;}
        #exampleModal .col{padding: 6px 3px;}
        #fill-basic-info{display: none;}
    </style>
{% endblock %}

{% block main %}
<div class="container">
    <div class="input-group">
        <h2 style="margin: auto;text-align: center">
            拜访记录
            <small class="text-muted">(<span id="total">{{ visited_records | length }}</span>)</small>
        </h2>
    </div>
    <div>
        <form class="form form-inline">

            <div class="input-group float-right h3 ml-auto">
                <input id="search-name-input" type="text" class="form-control" placeholder="搜索拜访记录">
                <button class="btn btn-primary">搜索</button>
            </div>
        </form>
    </div>
    <table class="table table-bordered  table-hover" id = "tab">
        <tr>
            <th>No.</th>
            <th>日期</th>
            <th>标题</th>
            <th>学校</th>
            <th>学院</th>
            <th>教师</th>
            <th>编辑</th>
        </tr>
        {% for record in visited_records %}
        <tr>
                <td>{{ loop.index }}</td>
                <td>{{ record.date }}</td>
                <td><a data-toggle="modal" data-target="#exampleModal">{{ record.title }}</a></td>
                <td>{{ record.school }}</td>
                <td>{{ record.institution }}</td>
                <td><a href="{{ url_for('scholar.scholar_info', teacher_id=record.teacher_id) }}">{{ record.teacher }}</a> </td>
                <td class="operation" data-id="{{ record._id }}">
                    <button class="btn btn-info btn-modify" data-toggle="modal">修改</button>
                    <button class="btn btn-danger btn-delete" type="button">删除</button>
                    <input type="hidden" class="detail" value="{{ record.content }}">
                </td>
        </tr>
        {% endfor %}
        <tr>
            <td colspan="7" id="add-new-record" data-toggle="modal" data-target="#exampleModal" onclick="wantToNewRecord($(this));"> +添加新纪录 </td>
        </tr>
    </table>

    <!-- 模态框（Modal） -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog " role="document">
            
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" id="csrf_token">
                        <div class="input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <span class="input-group-text ">日期</span>
                            </div>
                            <input id="date" class="form-control mod" type="date" name="date">
                        </div>
                        
                        <div class="input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <span class="input-group-text">标题</span>
                            </div>
                            <input type="text" id="title" class="form-control mod" placeholder="" aria-describedby="addon-wrapping">
                        </div>
                        
                        <div class="input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <span class="input-group-text">学校</span>
                            </div>
                            <select id="select-college">
                                {% for school in schools %}
                                    <option>{{ school }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                        <div class="input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <span class="input-group-text">学院</span>
                            </div>
                            <select id="select-institution">
                                {% for institution in institutions %}
                                    <option>{{ institution }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        
                        <div class="input-group flex-nowrap">
                            <div class="input-group-prepend">
                                <span class="input-group-text">教师</span>
                            </div>
                            <input type="text" name="teacher" id="teacher" class="form-control mod" placeholder="" aria-label="Username" aria-describedby="addon-wrapping">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" id="basic-addon" type="button">完善信息</button>
                            </div>
                        </div>
                        <div id="fill-basic-info">
                            <div class="form-row">
                                <div class="col">
                                    <input type="text" class="form-control" id="position" name="position" placeholder="行政职务，如 院长">
                                </div>
                                <div class="col">
                                    <input type="text" class="form-control" id="teacher-title" name="teacher-title" placeholder="职称，如 教授">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col">
                                    <input type="tel" id="telphone" name="telphone" class="form-control" placeholder="手机号">
                                </div>
                                <div class="col">
                                    <input type="email" id="email" name="email" class="form-control" placeholder="邮箱">
                                </div>
                            </div>
                           
                            <div class="form-row">
                                <div class="col">
                                    <input type="text" id="office-phone" name="office-phone" class="form-control" placeholder="办公室电话">
                                </div>
                                <div class="col">
                                    <input type="text" id="department" name="department" class="form-control" placeholder="所属学院下的系">
                                </div>
                            </div>
                            
                        </div>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text">内容</span>
                            </div>
                            <textarea name="content" rows="5" id="content" class="form-control mod" aria-label="With textarea"></textarea>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                    <button type="button" class="btn btn-primary preservation" onclick="saveVisitedRecord($(this))">保存</button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/visit_record.js') }}"></script>
{% endblock %}