web/blueprints/school.py
import json
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user

import web.service.school as school_service
from web.service.school_agent_service import agent_service
from web.utils import rich_abort

school_bp = Blueprint('school', __name__)


@school_bp.route('/<school>')
@login_required
def index(school):
    """
    显示该学校的所有学院和相关的信息 树图
    :param school:
    :return:
    """
    objects = school_service.get_school_info(school)
    if objects is None:
        rich_abort(404, '未找到该学校的信息，请确认学校名称后重试')
    subjects = []
    return render_template('school/index.html', school=school, objects=objects, subjects=subjects)


@school_bp.route('/get_institution_info', methods=["GET"])
@login_required
def get_institution_info():
    """
    获取重点学院和非重点学院
    :return:
    """
    school = request.args.get("school")
    data = school_service.get_total_institutions(school)
    return json.dumps({"success": True, "data": data})


@school_bp.route('/<school>/<institution>')
@login_required
def show_institution(school, institution):
    """
    显示某一学校的学院的相关信息 主要是院系中的团队 关系图
    :param school:
    :param institution:
    :return:
    """
    # 获取院系的关系网络
    graph_json = agent_service.get_relations(school, institution)
    if graph_json is False:
        rich_abort(404, '暂时没有该学院的社交网络，请确认名称或联系管理员')
    # 获取拜访次数
    subjects = school_service.get_related_teachers(current_user.related_teacher, graph_json)
    # 获取客观信息
    objects = school_service.get_institution_info(school, institution)
    if objects is None:
        rich_abort(404, '未找到关于该学校和学院的相关信息，请确认后重试')

    return render_template('school/institution.html', school=school, institution=institution,
                           objects=objects, subjects=subjects, graph_json=json.dumps(graph_json))


@school_bp.route('/<school>/<institution>/<int:team_index>')
@login_required
def show_team(school, institution, team_index):
    """
    显示某一个团队的相关信息 关系图
    :param school: 学校名
    :param institution: 学院名
    :param team_index: 团队的索引
    :return:
    """
    graph_data, objects = school_service.get_team(school, institution, team_index)
    # 学校或者是学院不存在
    if graph_data is False:
        rich_abort(404, '暂时没有该学院的社交网络，请确认名称或联系管理员')
    # 团队不存在
    core_node = graph_data['core_node']
    if len(core_node) == 0:
        rich_abort(404, '未找到该团队')
    # 获取当前用户的有联系的老师
    subjects = school_service.get_related_teachers(current_user.related_teacher, graph_data)

    return render_template('school/team.html', school=school, institution=institution,
                           graph_data=json.dumps(graph_data), core_node=core_node,
                           objects=objects, subjects=subjects)


@school_bp.route('/edit_institution',methods=['GET'])
@login_required
def edit_institution():
    """
    跳转到选择关注的学院页面
    :return:
    """
    school = request.args.get("cur_school")
    institution = school_service.get_edit_institution(school)
    return render_template("school/edit_institution.html",school=school,institution=institution)

@school_bp.route('/update_institution_select',methods=['GET'])
@login_required
def update_institution_select():
    """
    更新数据库中学院表中用户学院slect字段
    :return:
    """
    school = request.args.get("school")
    select_institution = request.args.get("institution")
    # 处理页面获取的所选学院的字符串为列表
    selected_institution = []
    for i in select_institution.strip("[").strip("]").split(","):
        selected_institution.append(i.replace("\"", "").strip())
    institution = []
    all_institution = school_service.get_all_institution(school)
    for i in selected_institution:
        institution.append([i,1])
        if i in all_institution:
            all_institution.remove(i)
    for j in all_institution:
        institution.append([j,0])
    try:
        school_service.update_institution_select(school,institution)
        return json.dumps({"success":True})
    except:
        return json.dumps({"success":False})

web/templates/school/base.html
{% extends 'base.html' %}

{% block styles %}
<style>
    #container{
        position: absolute;
        top: 120px;
        right: 0;
        bottom: 0;
        left: 0;
        z-index: -1;
    }
    .breadcrumb-nav{
        position: relative;
    }
    
    .edit-institution{
        position: absolute;
        top: 5px;
        right: 0.5rem;
    }
</style>
{% endblock %}


{% block main %}
<div id="container"></div>
<nav aria-label="breadcrumb" class="breadcrumb-nav">
    <ol class="breadcrumb">
        {% block breadcrum %}
        {% endblock %}
    </ol>
    {% block editInstitution %}
    {% endblock %}
</nav>
    {% block detail %}
    {% endblock %}
{% endblock %}

{% block scripts %}
    {{ super() }}

{% endblock %}

web/templates/school/edit_institution.html
{% extends 'school/base.html' %}

{% block title %}
    编辑学院
{% endblock %}

{% block styles %}
   <style>
    .checkbox{
        display: inline-block;
        padding-right: 50px;
        padding-top: 10px;
        font-size: 12px;
        zoom:150%;
    }
    </style>
{% endblock %}

{% block breadcrum %}
    <li class="breadcrumb-item"><a id="school" href="{{ url_for('school.index', school=school) }}">{{ school }}</a></li>
{% endblock %}

{% block detail%}
    <br>
    <div class="container">
        <h4>选择需要关注的学院</h4>
    <br>
      <h5>重点学院</h5>
      {% for i in institution.main_institution %}
            <div id="chkDiv" class="form-check checkbox" >
              <label class="form-check-label">
                  {% if i[1] == 1 %}
                    <input type="checkbox" checked name="institution" class="form-check-input" value="">{{ i[0] }}
                  {% else %}
                    <input type="checkbox" name="institution" class="form-check-input" value="">{{ i[0] }}
                  {% endif %}
              </label>
            </div>
      {% endfor %}
      <br><br><br>
      <h5>非重点学院</h5>
      {% for i in institution.dis_main_institution %}
            <div id="chkDiv" class="form-check checkbox">
              <label class="form-check-label">
                {% if i[1] == 1 %}
                    <input type="checkbox" checked name="institution" class="form-check-input" value="">{{ i[0] }}
                  {% else %}
                    <input type="checkbox" name="institution" class="form-check-input" value="">{{ i[0] }}
                  {% endif %}
              </label>
            </div>
      {% endfor %}
      <br><br>

    <button class="btn btn-primary" onclick="select_instituion()">提交</button>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script>
      /**
     *提交编辑学校结果
     */
    function select_instituion(){
        var id = document.getElementsByName('institution');
        var value = new Array();
        for(var i = 0; i < id.length; i++){
         if(id[i].checked) {
             value.push(id[i].nextSibling.data.replace(/\s+/g,""))
         }
        }
        let schoolName = document.getElementById("school").innerText
        $.ajax({
            type: "get",
            url: "update_institution_select",
            dataType: "json",
            data:{
                school: schoolName,
                institution: JSON.stringify(value)
            },
            success:function (response) {
                if(response.success){
                    toggle_alert(true, "", "提交成功！");
                }
                else{
                    toggle_alert(false, "", "提交失败！请稍后重试");
                }
            },
            error:function(error){
                toggle_alert(false, "", "请求失败！");
            }
        })
    }
    </script>
{% endblock %}

web/templates/school/index.html
{% extends 'school/base.html' %}

{% block title %}
    {{ school }}
{% endblock %}

{% block breadcrum %}
    <input hidden id="cur_school" value="{{ school }}">
    <li class="breadcrumb-item active" aria-current="page">{{ school }}</li>
{% endblock %}


{% block editInstitution %}
    <a href="/school/edit_institution?cur_school={{ school }}" target="_blank" class="edit-institution float-right btn btn-primary">编辑学院</a>
{% endblock %}
{% block detail %}

    <div class="float-right mt-5 mr-5">
        <p>
            <a class="btn btn-link" data-toggle="collapse" href="#object" role="button" aria-expanded="false" onclick="$('#subject').collapse('hide')">客观信息</a>
            <a class="btn btn-link" data-toggle="collapse" href="#subject" aria-expanded="false" onclick="$('#object').collapse('hide')">拜访次数
            </a>
        </p>
        <div class="collapse" id="object">
            <ul class="list-group">
                {% for name, num in objects %}
                    <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
                {% endfor %}
            </ul>
        </div>
        <div class="collapse" id="subject">
            <ul class="list-group">
                {% if subjects | length %}
                    {% for name, num in subjects %}
                        <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">无拜访人员</li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/echarts/4.2.1-rc1/echarts.min.js"></script>
    <script src="{{ url_for('static',filename='js/school/school.js') }}"></script>
    <script type="text/javascript">
        $('#object').collapse('toggle');
    </script>
{% endblock %}

web/templates/school/institution.html
{% extends 'school/base.html' %}

{% block title %}
    {{ school }}-{{ institution }}
{% endblock %}

{% block breadcrum %}
    <li class="breadcrumb-item"><a href="{{ url_for('school.index', school=school) }}">{{ school }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ institution }}</li>
{% endblock %}

{% block detail %}
<div class="float-right mt-5 mr-5">
    <p>
        <a class="btn btn-link" data-toggle="collapse" href="#object" role="button" aria-expanded="false" onclick="$('#subject').collapse('hide')">客观信息</a>
        <a class="btn btn-link" data-toggle="collapse" href="#subject" aria-expanded="false" onclick="$('#object').collapse('hide')">拜访次数
        </a>
    </p>
    <div class="collapse" id="object">
    <ul class="list-group">
        {% for name, num in objects %}
            <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
        {% endfor %}
    </ul>
    </div>
    <div class="collapse" id="subject">
    <ul class="list-group">
    {% if subjects | length %}
        {% for name, num in subjects %}
            <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
        {% endfor %}
    {% else %}
        <li class="list-group-item">无拜访人员</li>
    {% endif %}
    </ul>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/echarts/4.2.1-rc1/echarts.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/school/institution.js') }}"></script>
    <script type="text/javascript">
        let DATA = {{ graph_json | safe }};
        let SCHOOL_NAME= "{{ school }}";
        let INSTITUTION_NAME = "{{ institution }}";
        reloadGraph(DATA);
        $('#object').collapse('toggle');
    </script>
{% endblock %}

web/templates/school/team.html
{% extends 'school/base.html' %}

{% block title %}
    {{ school }}-{{ institution }}-{{ core_node }}团队
{% endblock %}

{% block breadcrum %}
    <li class="breadcrumb-item"><a href="{{ url_for('school.index', school=school) }}">{{ school }}</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('school.show_institution', school=school, institution=institution) }}"> {{ institution }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ core_node }}团队</li>
{% endblock %}

{% block detail %}
    <div class="float-right mt-5 mr-5">
        <p>
            <a class="btn btn-link" data-toggle="collapse" href="#object" role="button" aria-expanded="false" onclick="$('#subject').collapse('hide')">团队信息</a>
            <a class="btn btn-link" data-toggle="collapse" href="#subject" aria-expanded="false" onclick="$('#object').collapse('hide')">拜访次数
            </a>
        </p>
        <div class="collapse" id="object">
            <ul class="list-group">
                {% for name, num in objects.items() %}
                    <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
                {% endfor %}
            </ul>
        </div>
        <div class="collapse" id="subject">
            <ul class="list-group">
                {% if subjects | length %}
                    {% for name, num in subjects %}
                        <li class="list-group-item">{{ name }} <span class="badge badge-primary float-right">{{ num }}</span> </li>
                    {% endfor %}
                {% else %}
                    <li class="list-group-item">无拜访人员</li>
                {% endif %}
            </ul>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://cdn.bootcss.com/echarts/4.2.1-rc1/echarts.min.js"></script>
    <script type="text/javascript">
    let DATA = {{ graph_data | safe}};
    let SCHOOL_NAME = "{{ school }}";
    let INSTITUTION_NAME = "{{ institution }}";
    $('#object').collapse('toggle');
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/school/team.js') }}"></script>
{% endblock %}